name: first
on:
  push:
  workflow_dispatch:
jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    environment: env_test
    steps:
      - name: step one
        uses: actions/checkout@v4
      - name: step two
        run: env | sort
  job2:
    name: second job
    runs-on: windows-latest
    environment: env_test
    steps:
      - name: step one
        uses: actions/checkout@v4

